name: Light Bot

on:
  workflow_dispatch:

  schedule:
    - cron: "0 22-23 * * *"   # 00:00–01:59 Київ (раз на годину)
    - cron: "0 0-4 * * *"     # 02:00–06:00 Київ (раз на годину)

    - cron: "*/20 4-21 * * *" # 06:00–23:59 Київ (кожні 20 хв)

    - cron: "0 5 * * *"       # 07:00 Київ (примусовий)
    - cron: "0 21 * * *"      # 23:00 Київ (примусовий)


permissions:
  contents: write


jobs:
  run-bot:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install telethon requests

    - name: Run bot
      run: python bot.py

    - name: Save state.txt
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"

        git add state.txt || true

        git diff --cached --quiet || git commit -m "update state"

        git push || true
